// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/30/2025, 11:08:41 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/plugins/**/*.{js,ts,mjs}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/composables/**/*.{js,ts,mjs}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/utils/**/*.{js,ts,mjs}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Mai/Desktop/InsuraGuard/insuraguard-app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;